name: Build LuckyAI APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name:  Clonar o código
        uses: actions/checkout@v3

      - name:  Configurar JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name:  Permitir execução do Gradle
        run: chmod +x gradlew

      - name: Construir APK (modo release)
        run: ./gradlew assembleRelease

      - name: Fazer upload do APK gerado
        uses: actions/upload-artifact@v3
        with:
          name: LuckyAI-APK
          path: app/build/outputs/apk/release/app-release.apk
